#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _BK_gc_reg();
extern void _Ca_HVA_reg();
extern void _Ca_LVA_reg();
extern void _Cabuffer_gc_reg();
extern void _CaDynamics_reg();
extern void _Cav12_gc_reg();
extern void _Cav13_gc_reg();
extern void _Cav22_gc_reg();
extern void _Cav32_gc_reg();
extern void _HCN_gc_reg();
extern void _Ih_reg();
extern void _Im_reg();
extern void _Im_v2_reg();
extern void _ingauss_reg();
extern void _K_P_reg();
extern void _K_Pst_reg();
extern void _K_T_reg();
extern void _K_Tst_reg();
extern void _Kd_reg();
extern void _Kir21_gc_reg();
extern void _Kv11_gc_reg();
extern void _Kv14_gc_reg();
extern void _Kv21_gc_reg();
extern void _Kv2like_reg();
extern void _Kv3_1_reg();
extern void _Kv34_gc_reg();
extern void _Kv42_gc_reg();
extern void _Kv723_gc_reg();
extern void _na8st_gc_reg();
extern void _Nap_reg();
extern void _Nap_Et2_reg();
extern void _NaTa_reg();
extern void _NaTa_t_reg();
extern void _NaTg_reg();
extern void _NaTs_reg();
extern void _NaTs2_t_reg();
extern void _NaV_reg();
extern void _SK_reg();
extern void _SK2_gc_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," BK_gc.mod");
fprintf(stderr," Ca_HVA.mod");
fprintf(stderr," Ca_LVA.mod");
fprintf(stderr," Cabuffer_gc.mod");
fprintf(stderr," CaDynamics.mod");
fprintf(stderr," Cav12_gc.mod");
fprintf(stderr," Cav13_gc.mod");
fprintf(stderr," Cav22_gc.mod");
fprintf(stderr," Cav32_gc.mod");
fprintf(stderr," HCN_gc.mod");
fprintf(stderr," Ih.mod");
fprintf(stderr," Im.mod");
fprintf(stderr," Im_v2.mod");
fprintf(stderr," ingauss.mod");
fprintf(stderr," K_P.mod");
fprintf(stderr," K_Pst.mod");
fprintf(stderr," K_T.mod");
fprintf(stderr," K_Tst.mod");
fprintf(stderr," Kd.mod");
fprintf(stderr," Kir21_gc.mod");
fprintf(stderr," Kv11_gc.mod");
fprintf(stderr," Kv14_gc.mod");
fprintf(stderr," Kv21_gc.mod");
fprintf(stderr," Kv2like.mod");
fprintf(stderr," Kv3_1.mod");
fprintf(stderr," Kv34_gc.mod");
fprintf(stderr," Kv42_gc.mod");
fprintf(stderr," Kv723_gc.mod");
fprintf(stderr," na8st_gc.mod");
fprintf(stderr," Nap.mod");
fprintf(stderr," Nap_Et2.mod");
fprintf(stderr," NaTa.mod");
fprintf(stderr," NaTa_t.mod");
fprintf(stderr," NaTg.mod");
fprintf(stderr," NaTs.mod");
fprintf(stderr," NaTs2_t.mod");
fprintf(stderr," NaV.mod");
fprintf(stderr," SK.mod");
fprintf(stderr," SK2_gc.mod");
fprintf(stderr, "\n");
    }
_BK_gc_reg();
_Ca_HVA_reg();
_Ca_LVA_reg();
_Cabuffer_gc_reg();
_CaDynamics_reg();
_Cav12_gc_reg();
_Cav13_gc_reg();
_Cav22_gc_reg();
_Cav32_gc_reg();
_HCN_gc_reg();
_Ih_reg();
_Im_reg();
_Im_v2_reg();
_ingauss_reg();
_K_P_reg();
_K_Pst_reg();
_K_T_reg();
_K_Tst_reg();
_Kd_reg();
_Kir21_gc_reg();
_Kv11_gc_reg();
_Kv14_gc_reg();
_Kv21_gc_reg();
_Kv2like_reg();
_Kv3_1_reg();
_Kv34_gc_reg();
_Kv42_gc_reg();
_Kv723_gc_reg();
_na8st_gc_reg();
_Nap_reg();
_Nap_Et2_reg();
_NaTa_reg();
_NaTa_t_reg();
_NaTg_reg();
_NaTs_reg();
_NaTs2_t_reg();
_NaV_reg();
_SK_reg();
_SK2_gc_reg();
}
